[package]
name = "routefinder"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.4"
rand_core = "0.6.3"
clap = { version = "4.5.4", features = [ "derive" ] }
rlua = "0.17.0"
libm = "0.2.1"
lz4 = "1.23.2"
